pluginsGLPI/order

- ajax/dropdownReference.php
- front/export.php
- front/order.form.php
- inc/order.class.php
- inc/order_item.class.php
- inc/reference.class.php
Bug fix : 
- Add entity filter for reference dropdown loading
- Export csrf error : replace POST by GET
- Generation of ODT document : catch exceptions if field is not found
- Add manufacturer reference on order form
> Bug fix + add manufacturer reference

- ajax/dropdownReference.php
Problem with Discounted price tax free
fix #9
> Problem with Discounted price tax free & multiple price for a reference

- hook.php
- inc/reference.class.php
- setup.php
Search for manufacturer with a dropdown, search by type and itemtype.
> contribution for search on references

- ajax/dropdownReference.php
> select good price for item switch supplier id

- inc/surveysupplier.class.php
Notation rating is bad. It's on 5, not 10.
Regards
> Error in supplier notation

- inc/order.class.php
if order is cancel do not decrement total already used on budget form -> "order" tab
> if order is cancel do not decrement total already used

- inc/order.class.php
On budget form use taxe free for 'budget already used' on 'oerder' tab.
> On budget form use taxe free for 'budget already used'

- ajax/linkactions.php
- inc/link.class.php
- inc/order.class.php
Replace PR https://github.com/pluginsGLPI/order/pull/49/ from amma35
> Add Fields Location, group and status in the generation equipment.

- inc/order.class.php
- setup.php
Order and generate certificates
> Ability to order certificates

- front/order.form.php
> Wrong history when deleting a reference in an order fix #148

- inc/link.class.php
- inc/order_item.class.php
- inc/reception.class.php
> Harmonize assets name 

- inc/config.class.php
With this you can save the current order lifecycle settings
#191
> Save order lifecycle configuration when update

- inc/link.class.php
- inc/order_item.class.php
In Order item added Manufacturer Reference column.
In Associated items added Serial Number column.
#195
> Add Manufacturer Reference and Serial Number

- front/accountsection.form.php
- front/accountsection.php
- front/analyticnature.form.php
- front/analyticnature.php
- front/order.form.php
- hook.php
- inc/accountsection.class.php
- inc/analyticnature.class.php
- inc/config.class.php
- inc/order.class.php
- inc/order_item.class.php
- order.css
Hello,
This PR adds 2 specific fields : analytic nature (in order item) and account section (in order form). It provide two configuration options to make these 2 fields mandatory or not.
Have a nice day
Alan
> Add analytic nature and account section fields

- ajax/billactions.php
- ajax/linkactions.php
- inc/link.class.php
- inc/order.class.php
- inc/reference.class.php
- plugin.xml
- setup.php
- Use array conditions instead of string in Dropdown::show()
> GLPI 9.4 compatibility

- hook.php
> Fix undefined index in search result list

- inc/link.class.php
> fix generate item after take item

- inc/reference_supplier.class.php
Fixes "N/A" in reference supplier form and in reference history.
> Fix reference supplier name; fixes #221

- setup.php
Check that composer is executed prior to install
> require composer before insatll

- inc/link.class.php
> fix asset generation

- inc/config.class.php
- inc/order.class.php
- inc/order_item.class.php
- inc/order_supplier.class.php
- inc/reception.class.php
- inc/reference.class.php
- inc/reference_supplier.class.php
Required to enable autocomplete on GLPI 9.4.4+ (see https://github.com/glpi-project/glpi/commit/339b856273f2cf5cb409e6db1a2689a418c5a051)
> Whitelist autocomplete fields

- inc/link.class.php
- inc/order.class.php
- inc/order_item.class.php
- setup.php
- apply a global discount (retrieved in item lines)
> apply global discount to order's items

- inc/orderpayment.class.php
Changed the permission to allow to generate payment methods since the permission 'config' does not allow to add 
#275 #273
> Fix payment rightname

- inc/surveysupplier.class.php
Equalize the supplier quality score limit to 5 to avoid confusion.
> Equal limit of notes

- inc/reception.class.php
Should be reviewed without whitespaces changes.
> Fix first item reception

- ajax/dropdownReference.php
- ajax/inputnumber.php
- ajax/referencedetail.php
- hook.php
- inc/bill.class.php
- inc/order.class.php
- inc/order_item.class.php
- inc/profile.class.php
- inc/reference.class.php
- inc/reference_supplier.class.php
Fixes files from core
Fix display references
> Fixes For GLPI 10

- inc/order_item.class.php
Fix item add display for GLPI 10
> Fix Item Add Display

- inc/notificationtargetorder.class.php
> Fix exception on late orders notification sending

- inc/link.class.php
> Fix Delete Link with Item

- inc/config.class.php
- inc/link.class.php
- inc/order_item.class.php
Add possibility to specify immobilization number when generating items.
TODO : add a new translation with transifex : "Add immobilization number to item". This tranlation is used in inc/config.class.php
> add immobilization number when generating asset

- inc/menu.class.php
See glpi issue [#12370 ](https://github.com/glpi-project/glpi/issues/12370)
> Access ToSave Searches Lists

- inc/link.class.php
Replaces https://github.com/pluginsGLPI/order/pull/338 which I can no longer modify because it did not come from a fork.
> fix(generate item): error message with consumable

- CHANGELOG.md
- inc/order.class.php
- inc/order_item.class.php
This message is caused by the fact that we could add an order without "Product reference".
----
ref !31818
> Support 31818

- ajax/dropdownReference.php
- composer.json
- composer.lock
- front/order.form.php
- front/order_supplier.form.php
- front/reference.form.php
- front/surveysupplier.form.php
- hook.php
- inc/bill.class.php
- inc/config.class.php
- inc/link.class.php
- inc/order.class.php
- inc/order_item.class.php
- inc/order_supplier.class.php
- inc/preference.class.php
- inc/profile.class.php
- inc/reception.class.php
- inc/reference.class.php
- inc/reference_supplier.class.php
- inc/surveysupplier.class.php
- phpstan.neon
Refactor plugin in phpstan level 5
> Refractor phpstan level 5

- CHANGELOG.md
- inc/order_item.class.php
- templates/order_getitems.html.twig
- Feature : !35243
- Here is a brief description of what this PR does
Twig to sort on “ID” column in “Order items” tab (DataTable)
> Feat sort on id column linked item tab

- CHANGELOG.md
- inc/link.class.php
- inc/order_item.class.php
- templates/order_getitems.html.twig
- templates/order_link_item.html.twig
- It fixes !35243
- Here is a brief description of what this PR does
Apply feature https://github.com/pluginsGLPI/order/pull/417 in the associated items tab
Before : 
After :
> Feat - Sortable table in associated items tab

- ajax/dropdownReference.php
- ajax/dropdownSupplier.php
- composer.json
- composer.lock
- front/order.form.php
- front/reception.form.php
- generate/custom.php.example
- inc/bill.class.php
- inc/link.class.php
- inc/notificationtargetorder.class.php
- inc/order.class.php
- inc/order_item.class.php
- inc/order_supplier.class.php
- inc/reception.class.php
- inc/reference.class.php
- inc/reference_supplier.class.php
- inc/surveysupplier.class.php
- phpstan.neon
This pull request refactors the management of database queries across multiple files to improve code readability and maintainability by replacing the SQL fetchArray() / fetchAssoc() queries with a structured approach to building queries with criteria in array format. It also updates loops to use foreach instead of while for better PHP practices.
> Fix - Refreshing deprecated query functions
