pluginsGLPI/order

- generate/custom.php.example
Changes needed to be able to use this custom.php example file with recent GLPI & Order Management plugin (former file threw HTTP Error 500 with details about function calls causing problem in /var/log/httpd/error_log)
Remplace
- html_clean() by Html::clean()
- convDate() by Html::convDate()
- getLoginUserID() by Session::getLoginUserID()
- formatNumber() by Html::formatNumber()
> Obsolete functions name

- inc/orderinjection.class.php
- inc/referenceinjection.class.php
The static function getTable() was missing from both orderinjection.class.php and referenceinjection.class.php files causing wrong table names to be used in datainjection plugin
This solves issue #67
> Missing getTable function preventing data injection

- hook.php
Plugin installation doesn't create directories under glpi/plugins/_order
The following request create the missing directories, and copy the files from template, signature, logo and generate in the newly created directories.
> Create missing directories at install and move files

- generate/custom.php.example
There is no `{comment}` field in `example.odt` file, so users that just try to generate example have an error.
> Fix missing comment field in sample order template; fixes #172

- inc/surveysupplier.class.php
`check` functions uses reference for its third parameter, so it is not possible to pass a volatile array.
> Fix survey supplier tab: fixes #173

- inc/config.class.php
Users were not able to enable the "Document renaming" feature after commit 24d2350334f0ab7eaef014372da4946f9a2b3534. I put back corresponding configuration option to test this feature and it seems to work.
Feature is still enabled for users which enabled this feature before 0.85+1.1.
Enabling this feature has following effects.
1) All documents added to an order has their filename changed to `{$order_num}.{$file_extension}`. It can lead to duplicates filenames.
2) A prefix can be defined in an `Order` tab in document categories and will be added to all documents added to an order.
> Add ability to enable document renaming feature

- inc/reception.class.php
If the automatic asset generation is active, assets are wrongly generated for items of type `PluginOrderOther` and `PluginOrderReferenceFree`.
Manual generation is not possible as massive actions are not enabled for this kind of items due to https://github.com/pluginsGLPI/order/blob/develop/inc/link.class.php#L310.
> Prevent generation of items that are not assets; closes #113

- inc/order_item.class.php
`!=` operator was added recently and will be introduced in 9.3.1 version of GLPI. Using it in a previous version makes a request like ``WHERE `column` IN ('!=', 'value')``, which is the exact opposite as expected ``WHERE `column` != 'value'``.
> Fix delivery item count in GLPI 9.3.0; fixes #201

- inc/link.class.php
- inc/reception.class.php
see also #205 
I can't see any usage in massive action methods of the cleaned keys.
With this clean, we have "only" `8 + nb_items * 3` (instead *7)  in input vars passed within the massiveaction ajax POST
so we can now have 330 items for default 1000 in max_input_vars.
I can certainly remove also the two last:
- plugin_order_references_id
- itemtype
but it means doing getFromDB calls in massive action processing, so a much longer processing.
Or instead, maybe we can do the retrieval of additional data by a global query with a IN for all passed id.
> clean unused input vars, fix #69

- hook.php
- inc/reference.class.php
`itemtype` have to be list in additional fields to be available in giveItem method. It's key will be `ITEM_{$itemtype}_{$so_id}_{$additional_field_name}`.
> Fix order references search results; fixes #230

- inc/link.class.php
- inc/order_item.class.php
Order object has no `buy_date` fields, so infocom `buy_date` is generated using the `order_date` value from the order object. The problem is that sometimes, it may be required to be able to define a different value for `buy_date` and `order_date` in infocom fields, but this is prevented by plugin.
This PR removes the protection on `buy_date` infocom field.
Internal id: 15908.
> Remove buy_date protection

- inc/link.class.php
- inc/reception.class.php
Fix automatic asset generation.
1. Add missing itemtype.
2. Check existence of inputs prior to checking their value.
3. Prevent template state to be overrided.
> Fix automatic asset generation; see #234

- inc/config.class.php
- inc/order.class.php
Add message if order life cycle is not configured
> feat(core): display warning if plugin is not configured

- inc/order_item.class.php
8091161bd8b2c1910dc9bc07859bd03110994d1f introduced a minimum value of 0 for most inputs.
It seem that it may be useful to allow negative value for the "price" input as it allow to give some kind of discounts.
See !22108.
> Allow negative price

- inc/order_item.class.php
It is not possible to remove an asset from the order if it is reference free
The problem was that it always linked the search to the glpi_plugin_order_references table.
> Fix delete reference free

- inc/link.class.php
When auto generation is requested for name, serial and inventory number, the inventory number was missing on the created item.
> fix: auto inventory number

- inc/reception.class.php
Since this PR
https://github.com/glpi-project/glpi/pull/10975
And particulary this change
https://github.com/glpi-project/glpi/pull/10975/files#diff-284b41ead4d268948c291846bcb61a98c51a0eebb76968e6d09a40b485909777
```MassiveAction``` (to update reception status) no longer works
Originally plugin cast ```MassiveAction``` object to ```array``` to handle ```items``` key
```php
// from MassiveAction process, we get ma object, so convert it into array
if (is_object($params)) {
$ma      = $params;
$params2 = (array) $params;
}
```
But the variable is private now, it will have a weird key name (class + variable name) in the array.
Before  https://github.com/glpi-project/glpi/pull/10975
Casting MassiveAction Object to array return this
```
["items"]=> array(1) { ["PluginOrderReception"]=> …
```
> fix(massiveaction): use getter instead of cast object to array

- .gitignore
- inc/order_item.class.php
- templates/order_infocom.html.twig
Fix display of order information from infocom tab
Before : 
After : 
fix !24028
> Fix infocom order

- inc/reception.class.php
In case of multiple reference, 
```Order``` display only one reference
We need to open first to get second
Before : 
The second reference is embedded from the first
After :
> fix(html): close div

- inc/link.class.php
- inc/reception.class.php
use own ```transfer``` action because :
- ```MassivecAction``` are link to ```PluginOrderReception``` object (not ```PluginOrderOrder_Item```) and compute ```PluginOrderReception``` table instead of ```PluginOrderOrder_Item``` table and thrown error
```
[2022-05-25 07:54:58] glpisqllog.ERROR: DBmysql::query() in /home/stanislas/Teclib/dev/GLPI/10.0-bugfixes/src/DBmysql.php line 370
*** MySQL query error:
SQL: SELECT `glpi_plugin_order_receptions`.`id`, `glpi_plugin_order_receptions`.`name`, `entities`.`completename` AS `locname`, `entities`.`id` AS `entID` FROM `glpi_plugin_order_receptions` LEFT JOIN `glpi_entities` AS `entities` ON (`entities`.`id` = `glpi_plugin_order_receptions`.`entities_id`) WHERE `glpi_plugin_order_receptions`.`id` IN ('1', '2') ORDER BY `locname`, …
```
> fix(transfer): use own transfer action

- inc/link.class.php
"Reference free" items (which is not a correct translation of "Référence libre" IMO) can be used to add items to orders without defining their itemtypes.
Since these items do not have an itemtype, we can't generate any GLPI items for them on delivery.
This mean on the "Associated items" tab, there is no checkbox to run massive actions for these items:
For comparison, here is another order with real item references, you can see the checkboxed are available in this case:
So the TLDR is that reference free item cant be generated as the checkbox are not displayed (which is normal).
However, there is an option to enable auto generation on item delivery:
With this option active, the plugin will try to generate all items when they are marked as "delivered", even if they are reference free.
This …
> Fix auto generation for "reference free" items

- hook.php
- inc/other.class.php
Fix error from ```Invalid relations declared```
```
[2023-05-02 07:34:32] glpiphplog.WARNING:   *** PHP User Warning (512): Invalid relations declared between "glpi_plugin_order_othertypes" and "glpi_plugin_order_others" table. Target field "othertypes_id" is not a foreign key field. in /var/www/html/GLPI/src/DbUtils.php at line 2144
Backtrace :
src/DbUtils.php:2144                               trigger_error()
inc/db.function.php:585                            DbUtils->getDbRelations()
src/CommonDBTM.php:866                             getDbRelations()
src/CommonDBTM.php:788                             CommonDBTM->cleanRelationData()
src/CommonDBTM.php:2064                            CommonDBTM->deleteFromDB()
src/RuleMatchedLog.php:183                         CommonDBTM->delete()
``` …
> fix(core): fix invalid relation declared

- inc/order.class.php
- inc/order_item.class.php
The mandatory fields check blocked modifications when these fields had been entered beforehand.
What's more, it was marked as validated but nothing was recorded :
ref. : !30784
> fix: check mendatory fields

- CHANGELOG.md
- inc/order.class.php
Since GLPI 10.0, it was no longer possible to clone an order.
!31772
> fix: restores the ability to clone an order

- CHANGELOG.md
- inc/order.class.php
ref !31826
Fix error message during plugin update (since https://github.com/pluginsGLPI/order/pull/372) :
```
SQL Error "1062": Duplicate entry '0-PluginOrderOrder-1' for key 'unicity' in query "UPDATE `glpi_displaypreferences` SET `itemtype` = 'PluginOrderOrder' WHERE `itemtype` = '3150'"
In DBmysql.php line 1535:
update itemtype of table glpi_displaypreferences for PluginOrderOrder - Erreur durant l'éxecution de la requête : UPDATE `glpi_displaypreferences` SET `itemtype` = 'PluginOrderOrder' WHERE `itemtype` = '3150' - L'erreur est Duplicate entry '0-PluginOrderOrder-1' for key 'unicity'
```
> fix migration update

- front/signature.php
- inc/preference.class.php
- setup.php
https://github.com/pluginsGLPI/order/pull/408
> Update plugin extension value from string to array

- inc/order.class.php
- It fixes !35687
Once all items on the invoice have been paid, the status of the order changes to "Paid"
> fix: Paid invoice changes status to Paid

- CHANGELOG.md
- inc/order.class.php
- It fixes !36770
- The calculation of the total price of an order remains at 0 regardless of the status of the orders. For this calculation, only cancelled orders must not be price in the total calculation.
> fix: The calculation of the total price of the orders remained always at 0

- CHANGELOG.md
- inc/reception.class.php
- It fixes !35240
Remove icon from massive action
Icon are only allowed from single action
> Fix(UI): no icon from massiveaction (only for single action)

- CHANGELOG.md
- inc/order_item.class.php
- It fixes !38760
- The table that was supposed to display more details about the ordered reference did not display the correct reference.
Before
After
> fix(order-item): incorrect values shown when expanding all table rows
